package io.plotnik.entran;

import java.awt.Font;
import java.awt.FontFormatException;
import java.awt.GraphicsEnvironment;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.UnsupportedLookAndFeelException;

/**
 * Утилита для поиска соответствий между английским оригиналом и русским переводом.
 * 
 * Для работы с JSON можно использовать GSON:
 * - https://github.com/google/gson
 * - https://mvnrepository.com/artifact/com.google.code.gson/gson
 * 
 * Вместо TagSoup можно использовать JSoup:
 * - https://jsoup.org/
 * - https://mvnrepository.com/artifact/org.jsoup/jsoup
 * - https://mvnrepository.com/artifact/org.ccil.cowan.tagsoup/tagsoup
 * 
 * В качестве базы данных можно использовать SQLite:
 * - https://mvnrepository.com/artifact/org.xerial/sqlite-jdbc
 */        
public class EnTranFrame extends javax.swing.JFrame {

    public EnTranFrame() {
        initComponents();
        getContentPane().setBackground(Settings.background);
        enText.setBackground(Settings.background);
        setLocationRelativeTo(null);
    }
    
    public Font addFont(String ttfFile, int fontSize) throws FontFormatException, IOException {
        Font font = Font.createFont(Font.TRUETYPE_FONT, new File(ttfFile));
        Font sizedFont = font.deriveFont(Font.PLAIN, fontSize);
        GraphicsEnvironment ge = GraphicsEnvironment.getLocalGraphicsEnvironment();
        ge.registerFont(sizedFont);
        return sizedFont;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonPanel = new javax.swing.JPanel();
        prevRuButton = new javax.swing.JButton();
        nextRuButton = new javax.swing.JButton();
        nextButton = new javax.swing.JButton();
        addButton = new javax.swing.JButton();
        addNextButton = new javax.swing.JButton();
        prevButton = new javax.swing.JButton();
        aboutButton = new javax.swing.JButton();
        splitPane = new javax.swing.JSplitPane();
        textScrollPane = new javax.swing.JScrollPane();
        enText = new javax.swing.JLabel();
        editScrollPane = new javax.swing.JScrollPane();
        tranTextArea = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("EN TRAN");

        buttonPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        prevRuButton.setText("Prev RU");

        nextRuButton.setText("Next RU");

        nextButton.setText("Next");

        addButton.setText("Add");

        addNextButton.setText("Add Next");

        prevButton.setText("Prev");

        aboutButton.setText("About");

        javax.swing.GroupLayout buttonPanelLayout = new javax.swing.GroupLayout(buttonPanel);
        buttonPanel.setLayout(buttonPanelLayout);
        buttonPanelLayout.setHorizontalGroup(
            buttonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttonPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(aboutButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 643, Short.MAX_VALUE)
                .addComponent(prevButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nextButton)
                .addGap(18, 18, 18)
                .addComponent(prevRuButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nextRuButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addNextButton)
                .addContainerGap())
        );
        buttonPanelLayout.setVerticalGroup(
            buttonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttonPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(buttonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(prevRuButton)
                    .addComponent(nextRuButton)
                    .addComponent(nextButton)
                    .addComponent(addButton)
                    .addComponent(addNextButton)
                    .addComponent(prevButton)
                    .addComponent(aboutButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        splitPane.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);
        splitPane.setResizeWeight(1.0);

        textScrollPane.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        enText.setFont(new java.awt.Font("Liberation Serif", 0, 24)); // NOI18N
        enText.setText("en text");
        enText.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        enText.setOpaque(true);
        textScrollPane.setViewportView(enText);

        splitPane.setTopComponent(textScrollPane);

        tranTextArea.setColumns(20);
        tranTextArea.setRows(5);
        tranTextArea.setWrapStyleWord(true);
        editScrollPane.setViewportView(tranTextArea);

        splitPane.setBottomComponent(editScrollPane);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(splitPane, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1057, Short.MAX_VALUE)
                    .addComponent(buttonPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(splitPane, javax.swing.GroupLayout.DEFAULT_SIZE, 660, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EnTranFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EnTranFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EnTranFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EnTranFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EnTranFrame().setVisible(true);
            }
        });
    }
    
    public static void setLookAndFeel(String lfname) {
        for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
            if (lfname.equals(info.getName())) {
                try {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(EnTranFrame.class.getName()).log(Level.SEVERE, null, ex);
                } catch (InstantiationException ex) {
                    Logger.getLogger(EnTranFrame.class.getName()).log(Level.SEVERE, null, ex);
                } catch (IllegalAccessException ex) {
                    Logger.getLogger(EnTranFrame.class.getName()).log(Level.SEVERE, null, ex);
                } catch (UnsupportedLookAndFeelException ex) {
                    Logger.getLogger(EnTranFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
                break;
            }
        }        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton aboutButton;
    public javax.swing.JButton addButton;
    public javax.swing.JButton addNextButton;
    private javax.swing.JPanel buttonPanel;
    public javax.swing.JScrollPane editScrollPane;
    public javax.swing.JLabel enText;
    public javax.swing.JButton nextButton;
    public javax.swing.JButton nextRuButton;
    public javax.swing.JButton prevButton;
    public javax.swing.JButton prevRuButton;
    public javax.swing.JSplitPane splitPane;
    public javax.swing.JScrollPane textScrollPane;
    public javax.swing.JTextArea tranTextArea;
    // End of variables declaration//GEN-END:variables
}
